### ISSUE TITLE
Turkce karakter kullanimi

### ISSUE THREAD

**Issue by unicod3** [ikonur/yapilacak-listesi#1]
turkce karakter kullanimi modellerde sakincali bi islem, o karakterler ingilizce karakterlerle duzeltilmeli
https://github.com/ikonur/yapilacak-listesi/blob/34b070fab3b86847abb2afc08300ad036ee53855/data/models.py#L9
https://github.com/ikonur/yapilacak-listesi/blob/34b070fab3b86847abb2afc08300ad036ee53855/data/models.py#L10

**Comment by ikonur** [comment]
düzeltildi
